version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"  # Mở port 80 cho ứng dụng
    container_name: react_vite_dev
    environment:
      - NODE_ENV=production  # Chạy ứng dụng trong môi trường production
    restart: always
    networks:
      - react_network

networks:
  react_network:
    driver: bridge
