version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    container_name: react_vite_dev
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    restart: always
    networks:
      - react_network

networks:
  react_network:
    driver: bridge
